[package]
edition = "2021"
name = "ltpp"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = {version = "1.12", features = ["derive"]}
chrono = "0.4.31"
pollster = "0.3.0"
wgpu = "0.17.0"
winit = "0.28.6"
